version: '3.8'

services:
  ui:
    build:
      context: ./no-ocr-ui
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ""
        VITE_SUPABASE_ANON_KEY: ""
        VITE_REACT_APP_API_URI: "http://localhost:8000"
    env_file:
      - ./no-ocr-ui/.env
    ports:
      - "5173:5173"
    depends_on:
      - api

  api:
    build:
      context: ./no-ocr-api
      dockerfile: Dockerfile
    env_file:
      - ./no-ocr-api/.env
    volumes:
      - api-storage:/app/storage
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      QDRANT_HOST: "qdrant"
      
  qdrant:
    image: qdrant/qdrant:v1.12.5
    volumes:
      - qdrant-storage:/qdrant/storage
    ports:
      - "6333:6333"

volumes:
  api-storage:
  qdrant-storage:
