name: CI

on:
  push:
    branches:
      - main
      - no-ocr-dev
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push docker image UI
        uses: docker/build-push-action@v6
        with:
          context: no-ocr-ui
          push: true
          tags: ghcr.io/kyryl-opens-ml/no-ocr-ui:latest
          cache-from: type=registry,ref=ghcr.io/kyryl-opens-ml/no-ocr-ui:buildcache
          cache-to: type=registry,ref=ghcr.io/kyryl-opens-ml/no-ocr-ui:buildcache,mode=max

      - name: Build and push docker image API
        uses: docker/build-push-action@v6
        with:
          context: no-ocr-api
          push: true
          tags: ghcr.io/kyryl-opens-ml/no-ocr-api:latest
          cache-from: type=registry,ref=ghcr.io/kyryl-opens-ml/no-ocr-api:buildcache
          cache-to: type=registry,ref=ghcr.io/kyryl-opens-ml/no-ocr-api:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway
        run: rm -rf package-lock.json && npm i -g @railway/cli

      - name: Deploy UI
        run: railway redeploy --service app --yes
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 

      - name: Deploy API 
        run: railway redeploy --service api --yes
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}           