name: Test

on:
  push:
    branches: [ main, no-ocr-dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r no-ocr-api/requirements.txt
          pip install ruff pytest-cov
      - name: Run linters
        run: ruff check .
      - name: Run tests
        run: pytest --cov=no-ocr-api/np_ocr --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
